import { JobPost, ActiveCareSession, CareReport, PartnerProfile, Conversation } from './types';

export const INITIAL_PARTNER: PartnerProfile = {
  name: '김미숙',
  roleTitle: '전문 간병인 · 1급 요양보호사',
  avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=256&q=80',
  phone: '010-3849-****',
  isReceivingBids: true,
  currentRadiusKm: 5,
  brix: 18.6,
  brixGrade: '명품 샤인머스캣',
  totalMatches: 68,
  rating: 4.95,
  reviewCount: 52,
  experienceYears: 6,
  licenses: [
    { name: '요양보호사 1급', level: '보건복지부 공인', verified: true, issuedDate: '2020.04.15' },
    { name: '간호조무사', level: '한국보건의료인국가시험원', verified: true, issuedDate: '2018.11.20' },
    { name: '병원동행 매니저 1급', level: '대한병원동행협회', verified: true, issuedDate: '2023.02.10' },
  ],
  insurance: {
    verified: true,
    provider: '현대해상 전문인 배상책임보험',
    coverageAmount: '최대 1억 원',
    expiryDate: '2027.01.31 (자동 갱신)',
  },
  settlement: {
    withdrawableAmount: 840000,
    pendingEscrowAmount: 441000,
    monthlyTotal: 3420000,
    bankAccount: '토스뱅크 1000-2938-4821',
  },
  reviewTags: [
    { tag: '시간 약속을 철저히 지켜요', count: 46 },
    { tag: '의사 소견을 꼼꼼하게 메모해요', count: 39 },
    { tag: '환자 상태를 가족처럼 챙겨요', count: 34 },
    { tag: '석션/휠체어 이동이 능숙해요', count: 28 },
    { tag: '친절하고 배려심이 깊어요', count: 25 },
  ],
  brixHistory: [
    { id: 'b1', reason: '서울아산병원 3일 케어 5점 후기 수령', change: 0.5, date: '2026.09.02' },
    { id: 'b2', reason: 'Door-to-Door 6단계 실시간 트래킹 정시 이행', change: 0.3, date: '2026.09.02' },
    { id: 'b3', reason: 'AI Care Report 꼼꼼한 진료 전달사항 작성', change: 0.2, date: '2026.08.30' },
    { id: 'b4', reason: '보호자 단골 지정 매칭 성사', change: 0.8, date: '2026.08.28' },
    { id: 'b5', reason: '자격증 갱신 및 배상책임보험 검증 승인', change: 0.5, date: '2026.08.20' },
  ],
};

export const INITIAL_JOB_POSTS: JobPost[] = [
  {
    id: 'job-1',
    title: '서울아산병원 신관 내과 외래 진료 동행 및 약국 수령',
    patientName: '박*순',
    patientAge: 76,
    patientGender: '여',
    careType: 'escort',
    hospitalName: '서울아산병원',
    hospitalRoom: '신관 3층 소화기내과',
    locationArea: '서울 송파구 풍납동',
    distanceKm: 2.3,
    etaMinutes: 12,
    mobility: 'wheelchair',
    specialCares: ['휠체어 이승', '석션(가래흡인)', '낙상 주의'],
    scheduleDates: '2026.09.05 (토)',
    scheduleTime: '09:00 ~ 14:00 (5시간)',
    durationDays: 1,
    targetBudget: 110000,
    currentBidsCount: 3,
    guardianName: '최*영',
    guardianRelation: '딸',
    urgentNotice: '진료 예약 10:15 / 복용 중인 약 리스트 지참 필요',
    description: '어머니께서 무릎 수술 후 휠체어 이용 중이십니다. 잠실동 자택에서 픽업하여 아산병원 진료 후 처방전 수령 및 귀가까지 동행 부탁드립니다. 석션 가능하신 분 우대합니다.',
    status: 'open',
    createdAt: '15분 전',
    myBid: {
      id: 'bid-my-1',
      jobId: 'job-1',
      proposedAmount: 115000,
      appealTags: ['석션 케어 5년차', '병원동행 전문', '응급처치 수료'],
      guardianMessage: '안녕하세요 보호자님! 아산병원 외래 동행 경험이 풍부하며, 휠체어 안전 이승과 필요시 석션 케어 완벽히 지원 가능합니다.',
      createdAt: '10분 전',
      status: 'pending',
    },
  },
  {
    id: 'job-2',
    title: '강남세브란스병원 정형외과 입원 환자 24시간 간병',
    patientName: '이*호',
    patientAge: 69,
    patientGender: '남',
    careType: 'hospital',
    hospitalName: '강남세브란스병원',
    hospitalRoom: '본관 61병동 602호',
    locationArea: '서울 강남구 도곡동',
    distanceKm: 4.8,
    etaMinutes: 22,
    mobility: 'bedridden',
    specialCares: ['와상 체위변경', '소변줄/장루', '기저귀 케어'],
    scheduleDates: '2026.09.06 ~ 09.09 (3일간)',
    scheduleTime: '24시간 상주',
    durationDays: 3,
    targetBudget: 420000,
    currentBidsCount: 5,
    guardianName: '이*진',
    guardianRelation: '아들',
    description: '고관절 골절 수술 후 절대안정 상태입니다. 2시간마다 체위 변경 및 기저귀/소변줄 비우기 꼼꼼히 해주실 1급 요양보호사 선생님을 모십니다.',
    status: 'open',
    createdAt: '32분 전',
  },
  {
    id: 'job-3',
    title: '삼성서울병원 인공신장실 혈액투석 동행 케어',
    patientName: '정*수',
    patientAge: 71,
    patientGender: '남',
    careType: 'escort',
    hospitalName: '삼성서울병원',
    hospitalRoom: '별관 2층 인공신장실',
    locationArea: '서울 강남구 일원동',
    distanceKm: 3.5,
    etaMinutes: 16,
    mobility: 'assisted',
    specialCares: ['투석 동행', '혈압 모니터링', '부축 보행'],
    scheduleDates: '2026.09.07 (월)',
    scheduleTime: '13:00 ~ 18:00 (5시간)',
    durationDays: 1,
    targetBudget: 120000,
    currentBidsCount: 2,
    guardianName: '김*숙',
    guardianRelation: '배우자',
    urgentNotice: '투석 후 저혈압 어지럼증 주의',
    description: '정기 주 3회 투석 중이시며, 투석 종료 후 기운이 없으셔서 휠체어/부축 이동이 꼭 필요합니다. 자택(수서동)까지 안전 귀가 도와주실 분 희망합니다.',
    status: 'open',
    createdAt: '1시간 전',
  },
  {
    id: 'job-4',
    title: '송파구 문정동 자택 일상 회복 및 식사 보조 케어',
    patientName: '한*자',
    patientAge: 82,
    patientGender: '여',
    careType: 'home',
    homeAddress: '서울 송파구 문정동 래미안아파트',
    locationArea: '서울 송파구 문정동',
    distanceKm: 3.1,
    etaMinutes: 14,
    mobility: 'assisted',
    specialCares: ['치매/섬망', '식사 보조', '복약 지도'],
    scheduleDates: '2026.09.08 (화)',
    scheduleTime: '09:00 ~ 13:00 (4시간)',
    durationDays: 1,
    targetBudget: 90000,
    currentBidsCount: 1,
    guardianName: '박*민',
    guardianRelation: '며느리',
    description: '경증 치매 증상이 있으시나 말씀은 잘 나누십니다. 점심 식사 차림 및 혈압약 복용 챙겨주시고 30분 실내 가벼운 걷기 운동 도와주실 분 구합니다.',
    status: 'open',
    createdAt: '2시간 전',
  },
];

export const INITIAL_ACTIVE_SESSION: ActiveCareSession = {
  id: 'session-active-1',
  jobId: 'job-today',
  patientName: '최영자 님 (78세/여)',
  guardianName: '최민수 님 (아들)',
  guardianPhone: '010-8274-1928',
  hospitalName: '서울아산병원 동관',
  hospitalDept: '심장내과 외래진료실',
  scheduleDate: '2026년 9월 4일 (오늘)',
  currentStepIndex: 2, // 3rd step active (진료/접수 진행)
  steps: [
    {
      step: 1,
      key: 'start',
      title: '출발 완료',
      subTitle: '자택에서 어르신 모시고 출발',
      icon: '🚗',
      completed: true,
      time: '오전 09:10',
      memo: '잠실엘스 아파트 102동 1층에서 어르신 휠체어로 탑승 완료했습니다.',
    },
    {
      step: 2,
      key: 'arrived_hospital',
      title: '병원 도착',
      subTitle: '병원 로비 도착 및 휠체어 안전 이승',
      icon: '🏥',
      completed: true,
      time: '오전 09:35',
      memo: '아산병원 동관 지하 주차장 하차 후 2층 심장내과 접수처 대기 중입니다.',
      photoUrl: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?auto=format&fit=crop&w=400&q=80',
    },
    {
      step: 3,
      key: 'clinic',
      title: '진료·검사 진행',
      subTitle: '심전도 검사 및 주치의 상담',
      icon: '🩺',
      completed: false,
      time: '진행 중',
      memo: '10:00 심전도 검사 마쳤으며 교수님 진료실 앞 대기 중입니다.',
    },
    {
      step: 4,
      key: 'pharmacy',
      title: '약국 수령',
      subTitle: '원외 처방전 접수 및 복약 안내문 확인',
      icon: '💊',
      completed: false,
    },
    {
      step: 5,
      key: 'heading_home',
      title: '귀가 진행',
      subTitle: '차량 탑승 후 안전 귀가 이동',
      icon: '🏠',
      completed: false,
    },
    {
      step: 6,
      key: 'completed',
      title: '케어 완료',
      subTitle: '자택 침상 안치 및 최종 상태 보고',
      icon: '✅',
      completed: false,
    },
  ],
};

export const INITIAL_CARE_REPORT: CareReport = {
  id: 'report-1',
  jobId: 'job-today',
  patientName: '최영자 님',
  caremateName: '김미숙 케어메이트',
  date: '2026.09.04',
  hospitalName: '서울아산병원 심장내과',
  doctorFeedback: '심전도 결과는 3개월 전과 비교하여 안정적인 상태 유지 중입니다. 최근 호소하셨던 계단 오를 때의 숨참 증상은 기온 변화에 따른 일시적 현상으로 판단되며, 현재 약물 용량을 유지하면서 3개월 뒤 재검사 진행하기로 하였습니다.',
  medicationInstructions: '기존 혈압약 및 항혈소판제 아침 식후 30분 1포 복용. 특히 이뇨제 성분이 포함되어 있으므로 저녁 늦게 복용하지 않도록 주의가 필요합니다. 두통이나 현기증 발생 시 즉시 병원 문의 요망.',
  vitalSigns: {
    temp: '36.5 ℃',
    bloodPressure: '124 / 78 mmHg',
    mealIntake: '전부 드심',
    bowelMovement: '정상 배변',
    conditionNote: '어르신 기분 밝으셨으며 이동 간 어지러움 없이 안정적으로 보행 및 진료를 마쳤습니다.',
  },
  aiGeneratedSummary: '🌿 [포도당 청포도 AI Care Report 요약]\n1. 심장내과 주치의 소견: 심전도 검사상 이전 상태 양호하게 유지 중이며 처방약 변경 없이 유지.\n2. 처방전 및 복약: 90일 치 혈압/혈관 순환제 아산정문약국에서 수령 완료.\n3. 컨디션: 활력징후(체온 36.5℃, 혈압 124/78) 지표 최상, 귀가 후 따뜻한 물과 점심 식사 완식.',
  nextAppointment: '2026.12.04 (금) 10:30 서울아산병원 심장내과',
  isAiGenerated: true,
  isSharedWithFamily: true,
  sharedAt: '2026.09.04 13:45',
};

export const INITIAL_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv-1',
    jobId: 'job-1',
    guardianName: '최민수 보호자님',
    guardianRelation: '아들 (환자: 최영자 님)',
    patientName: '최영자 님',
    careTitle: '서울아산병원 심장내과 외래진료 동행',
    lastMessage: '네 선생님, 오늘 진료와 약국 수령까지 정말 든든했습니다! 감사합니다.',
    lastTime: '오후 1:50',
    unreadCount: 0,
    matchingStatus: 'paid',
    messages: [
      {
        id: 'm1',
        sender: 'system',
        text: '🔒 보호자님과의 1:1 안심 채팅이 시작되었습니다. 개인 전화번호는 전달되지 않으니 안심하세요.',
        timestamp: '오전 08:30',
        type: 'notice',
      },
      {
        id: 'm2',
        sender: 'guardian',
        text: '안녕하세요 김미숙 선생님, 오늘 저희 어머니 휠체어 이동 시 무릎에 무리가 가지 않도록 천천히 부탁드립니다.',
        timestamp: '오전 08:32',
      },
      {
        id: 'm3',
        sender: 'caremate',
        text: '안녕하세요 보호자님! 걱정 마세요. 휠체어 안전 이승과 완충 쿠션 준비하여 부드럽게 이동 도와드리겠습니다.',
        timestamp: '오전 08:35',
      },
      {
        id: 'm4',
        sender: 'system',
        text: '📋 간병 확정서가 생성되었습니다. 결제가 완료되면 에스크로에 안전하게 보관됩니다.',
        timestamp: '오전 08:40',
        type: 'invoice',
        invoiceData: {
          id: 'inv-101',
          careTitle: '서울아산병원 외래 진료 동행 (5시간)',
          period: '2026.09.04 (금)',
          dailyRate: 110000,
          days: 1,
          careAmount: 110000,
          platformFee: 5500,
          totalAmount: 115500,
          isPaid: true,
        },
      },
      {
        id: 'm5',
        sender: 'guardian',
        text: '네 선생님, 오늘 진료와 약국 수령까지 정말 든든했습니다! 감사합니다.',
        timestamp: '오후 1:50',
      },
    ],
  },
  {
    id: 'conv-2',
    jobId: 'job-2',
    guardianName: '이동진 보호자님',
    guardianRelation: '아들 (환자: 이영호 님)',
    patientName: '이영호 님',
    careTitle: '강남세브란스병원 24시간 입원 간병 3일',
    lastMessage: '선생님, 혹시 602호 병실 출입 바코드 등록은 어떻게 진행하면 될까요?',
    lastTime: '오전 11:20',
    unreadCount: 1,
    matchingStatus: 'consulting',
    messages: [
      {
        id: 'm2-1',
        sender: 'system',
        text: '🔒 포도당 안심 채팅방입니다. 안전한 에스크로 거래를 이용해 주세요.',
        timestamp: '오전 10:15',
        type: 'notice',
      },
      {
        id: 'm2-2',
        sender: 'caremate',
        text: '보호자님 안녕하세요! 제안서 확인해 주셔서 감사합니다. 고관절 수술 후 와상 체위 변경 꼼꼼하게 도와드릴 수 있습니다.',
        timestamp: '오전 10:18',
      },
      {
        id: 'm2-3',
        sender: 'guardian',
        text: '선생님, 혹시 602호 병실 출입 바코드 등록은 어떻게 진행하면 될까요?',
        timestamp: '오전 11:20',
      },
    ],
  },
];
